Repository palantir/cassandra, pull requests merged in 2023-08, with the labels that each got.

#425 Upgrade Snakeyaml to 2.1
  build.xml
  lib/licenses/snakeyaml-2.1.txt
  lib/snakeyaml-1.33.jar
  lib/snakeyaml-2.1.jar
  src/java/org/apache/cassandra/config/YamlConfigurationLoader.java
  tools/stress/src/org/apache/cassandra/stress/StressProfile.java
Labels: merge when ready, autorelease

#426 Implement the CassandraInitializer service for external initialization
  src/java/org/apache/cassandra/service/CassandraDaemon.java
  src/java/org/apache/cassandra/service/CassandraInitializer.java
Labels: merge when ready, autorelease

#434 Add missing distribution dependencies to cassandra-all
  build.xml
Labels: merge when ready

#431 Bumping guava from 16.0 to 32.1.2-jre
  bin/cassandra.bat
  bin/cassandra.in.sh
  build.xml
  conf/cassandra-env.ps1
  conf/cassandra-env.sh
  debian/cassandra.in.sh
  lib/failureaccess-1.0.1.jar
  lib/guava-16.0.jar
  lib/guava-32.1.2-jre.jar
  lib/licenses/failureaccess-1.0.1.txt
  lib/licenses/guava-16.0.txt
  lib/licenses/guava-32.1.2-jre.txt
  redhat/cassandra.in.sh
  src/java/org/apache/cassandra/cache/AutoSavingCache.java
  src/java/org/apache/cassandra/config/ColumnDefinition.java
  src/java/org/apache/cassandra/config/KSMetaData.java
  src/java/org/apache/cassandra/config/TriggerDefinition.java
  src/java/org/apache/cassandra/cql3/ColumnSpecification.java
  src/java/org/apache/cassandra/cql3/selection/Selection.java
  src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
  src/java/org/apache/cassandra/db/ColumnFamilyStore.java
  src/java/org/apache/cassandra/db/DataRange.java
  src/java/org/apache/cassandra/db/DeletionInfo.java
  src/java/org/apache/cassandra/db/RangeSliceCommand.java
  src/java/org/apache/cassandra/db/RangeTombstoneList.java
  src/java/org/apache/cassandra/db/SliceByNamesReadCommand.java
  src/java/org/apache/cassandra/db/SliceFromReadCommand.java
  src/java/org/apache/cassandra/db/filter/ExtendedFilter.java
  src/java/org/apache/cassandra/db/filter/NamesQueryFilter.java
  src/java/org/apache/cassandra/db/filter/SliceQueryFilter.java
  src/java/org/apache/cassandra/db/index/SecondaryIndex.java
  src/java/org/apache/cassandra/hadoop/ColumnFamilyRecordReader.java
  src/java/org/apache/cassandra/io/sstable/Descriptor.java
  src/java/org/apache/cassandra/io/sstable/format/SSTableFormat.java
  src/java/org/apache/cassandra/locator/InetAddressAndPort.java
  src/java/org/apache/cassandra/locator/TokenMetadata.java
  src/java/org/apache/cassandra/repair/RepairJob.java
  src/java/org/apache/cassandra/repair/RepairMessageVerbHandler.java
  src/java/org/apache/cassandra/repair/RepairRunnable.java
  src/java/org/apache/cassandra/repair/RepairSession.java
  src/java/org/apache/cassandra/service/ActiveRepairService.java
  src/java/org/apache/cassandra/service/StorageService.java
  src/java/org/apache/cassandra/streaming/StreamManager.java
  src/java/org/apache/cassandra/streaming/StreamResultFuture.java
  src/java/org/apache/cassandra/utils/IntervalTree.java
  test/unit/org/apache/cassandra/streaming/StreamingTransferTest.java
Labels: merge when ready, autorelease

#436 Backport CASSANDRA-15595
  src/java/org/apache/cassandra/io/compress/CompressionMetadata.java
Labels: merge when ready, autorelease, backport
