Repository palantir/cassandra, pull requests merged in 2023-03, with the labels that each got.

#391 Add is_new_cluster StorageService endpoint
  src/java/org/apache/cassandra/service/StorageService.java
  src/java/org/apache/cassandra/service/StorageServiceMBean.java
Labels: wip

#393 Add metric for tracking compactions of large partitions
  src/java/org/apache/cassandra/io/sstable/format/big/BigTableWriter.java
  src/java/org/apache/cassandra/metrics/ColumnFamilyMetrics.java
Labels: merge when ready, autorelease

#394 Restrict some cipher suites
  src/java/org/apache/cassandra/config/EncryptionOptions.java
  src/java/org/apache/cassandra/security/SSLFactory.java
  test/unit/org/apache/cassandra/security/SSLFactoryTest.java
Labels: merge when ready
